workflows:
  hospital_finder_workflow:
    name: Hospital Finder Workflow
    environment:
      groups:
        - app_store_connect
    scripts:
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Build Android
        script: |
          flutter build apk --release
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/**/outputs/**/*.apk
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your_email@example.com
      app_store_connect:
        apple_id: your_apple_id@example.com
        password: $APP_STORE_CONNECT_PASSWORD
